#!/system/bin/sh

config=/res/synapse/config.json
action=/res/synapse/actions

if [ ! -e $config ]; then
	if [ -d /sys/block/mmcblk1 ]; then
		mount -t rootfs -o rw,remount rootfs
	    source /res/synapse/config.json.generate > /$config
		mount -t rootfs -o ro,remount rootfs
	else
		mount -t rootfs -o rw,remount rootfs
	    source /res/synapse/config.json.xenerate > /$config
		mount -t rootfs -o ro,remount rootfs
	fi
	chmod -R 775 /res/synapse
	chmod 775 /sbin/uci
fi

case $1 in
config)
  cat $config
  ;;
configpath)
  echo $config
  ;;
actionpath)
  echo $action
  ;;
reset)
  rm -f $config
  ;;
esac
